name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Dependencies
      run:
          #Update Build Script Permissions and run Build Script 
          |
          chmod +x .github/workflows/build.sh
          .github/workflows/build.sh

    - name: Deploy to Raspberry Pi
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.RASPBERRY_PI_HOST }}
        username: ${{ secrets.RASPBERRY_PI_USERNAME }}
        password: ${{ secrets.RASPBERRY_PI_PASSWORD }}
        source: "./"
        target: "/var/www/wp-content/themes/groundlevel/"