name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install NVM
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

    - name: Set up Node.js 15
      run: nvm install 15 && nvm use 15

    - name: Install dependencies
      run: npm ci

    - name: Build production assets
      run: npm run prod

    - name: List files in theme directory
      run: ls -la wp-content/themes/groundlevel/

    - name: Deploy to Raspberry Pi
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.RASPBERRY_PI_HOST }}
        username: ${{ secrets.RASPBERRY_PI_USERNAME }}
        password: ${{ secrets.RASPBERRY_PI_PASSWORD }}
        source: "./"
        target: "/var/www/wp-content/themes/groundlevel/"