name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nodejs npm
        npm install

    - name: Build
      run: |
        cd wp-content/themes/groundlevel
        npm run build

    - name: Deploy
      uses: appleboy/ssh-action@v0.3.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          sudo rsync -avz --delete --exclude '.git*' --exclude 'node_modules' ${{ github.workspace }}/wp-content/themes/groundlevel/ /var/www/html/wp-content/themes/groundlevel/
